### ISSUE TITLE
Check for presence of env vars in main function

### ISSUE THREAD

**Issue by ashwinimanoj** [infraspecdev/spellcheck-action#4]
https://github.com/infraspecdev/spellcheck-action/blob/5ffc9e0b81b75fac3d444f2135573c9ccecbd80c/src/spell_check.py#L194

Right now the env vars are scattered around the application. Could you check for this at the beginning and pass the vars to relevant functions? 

A config object with all required configuration also would be a good option, which can further have objects to group together specific functions, for e.g. as shown below, that can be passed through the lifecycle of the application.

The class can have validations check for each attribute

```
class Config:
    def __init__(self, gh_conf, log_conf):
        self.gh_conf = gh_conf  # equivalent to GithubConfig
        self.log_conf = log_conf  # equivalent to LogConfig
```

**Comment by Rahul-4480** [comment]
centralized the config env variables f78548ba6a66d8827eec5666ccfcc4b8e73131a5
