### ISSUE TITLE
verify spell check github action has made the comment before deletion 

### ISSUE THREAD

**Issue by ashwinimanoj** [infraspecdev/spellcheck-action#6]
https://github.com/infraspecdev/spellcheck-action/blob/5ffc9e0b81b75fac3d444f2135573c9ccecbd80c/src/spell_check.py#L116

Right now existing comments are deleted for a pr, this might result in deleting other relevant comments made by users/other actions/bots. Instead suggest doing the following: 

1. Check for comments were made by spellcheck-action 
2. Mark the comment as resolved 

This way we will preserve history of actions taken with a pr

**Comment by Rahul-4480** [comment]
GitHub’s API doesn’t directly support marking comments as "resolved," , the only alternative is that we have to edit comments with a message that suggests they are resolved, which i think is not feasible idea ..!

**Comment by ashwinimanoj** [comment]
Sure, then could we check that comments are made by github-action to ensure that we don't delete other relevant comments?

**Comment by Rahul-4480** [comment]
comments made by github-actions[bot] are deleted and not the other relevant comments https://github.com/infraspecdev/spellcheck-action/pull/12

**Comment by ashwinimanoj** [comment]
@Rahul-4480 any way to ensure we are only deleting comments made by spell check bot? 
can you verify this by using another action and see if spell check deletes that comment?

**Comment by Rahul-4480** [comment]
yes we have verified it and the action only deletes the comment made by spell check bot
