### ISSUE TITLE
Do we need `save_result` ? Don't seem to be using it anywhere else

### ISSUE THREAD

**Issue by ashwinimanoj** [infraspecdev/spellcheck-action#7]
https://github.com/infraspecdev/spellcheck-action/blob/5ffc9e0b81b75fac3d444f2135573c9ccecbd80c/src/spell_check.py#L154

**Comment by rohit-ng** [comment]
Removed the save_result function b29d1995f3e72bea6e19642a1b6f3b5ec06222ab
