### ISSUE TITLE
Make `hasIssues` configurable

### ISSUE THREAD

**Issue by ashwinimanoj** [infraspecdev/spellcheck-action#8]
https://github.com/infraspecdev/spellcheck-action/blob/5ffc9e0b81b75fac3d444f2135573c9ccecbd80c/src/spell_check.py#L180

Could we take in config, say `failOnSpelling: true`, `failOnGrammar: true` and use that to set `hasIssues`?

**Comment by Rahul-4480** [comment]
made the failOnSpelling , failOnGrammar and failOnBoth configurable 3409653177b0a705548747b5d9792399fd88ea9f

**Comment by ashwinimanoj** [comment]
Could you change the input parameter to failForAll instead of failOnBoth?

**Comment by Rahul-4480** [comment]
renamed failonBoth to failForAll b8943dc65f32f309f8b62b1c79bd21e208f55020

**Comment by ashwinimanoj** [comment]
The conditions for failure should check if either failFor<value> is set or failForAll is set.

**Comment by ashwinimanoj** [comment]
What I meant is `failForAll` should be considered as a catch all (i.e. by default check for all types of issues), and not a to be considered as a separate type of issue. 

```
1  if category == "spelling issue" and self.config.spell_check["failOnSpelling"]:
2                   self.has_issues = True
3                elif category == "grammar issue" and self.config.spell_check["failOnGrammar"]:
4                  self.has_issues = True
5              elif category == "both" and self.config.spell_check["failForAll"]:
6                   self.has_issues = True
```

`line 1` should look like:
```
if category == "spelling issue" and (self.config.spell_check["failOnSpelling"] or  self.config.spell_check["failForBoth"]):
2                   self.has_issues = True
```
This should be done for line 3 and addressed in line 4 as well. It's like the fizzbuzz problem

**Comment by rohit-ng** [comment]
If we implement the changes as suggested, then if `failOnGrammar` is `False` and `failForAll` is `True`, the condition for `category == "grammar issue"` will still be executed due to the `failForAll` check.

**Comment by ashwinimanoj** [comment]
Yes, `failForAll` will act like "turn everything on", so if we bring in new types in future (not sure what they might be yet), they still fail the PR. Thinking over it some more, maybe failing on everything is not required. Removing it sounds like a better option. Go ahead with that.

**Comment by Rahul-4480** [comment]
removed the failForAll config https://github.com/infraspecdev/spellcheck-action/pull/16
